// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// mu_SR
NumericVector mu_SR(double a_0, double a_1, double a_2, double a_3, NumericVector d);
RcppExport SEXP _CppTrials_mu_SR(SEXP a_0SEXP, SEXP a_1SEXP, SEXP a_2SEXP, SEXP a_3SEXP, SEXP dSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type a_0(a_0SEXP);
    Rcpp::traits::input_parameter< double >::type a_1(a_1SEXP);
    Rcpp::traits::input_parameter< double >::type a_2(a_2SEXP);
    Rcpp::traits::input_parameter< double >::type a_3(a_3SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type d(dSEXP);
    rcpp_result_gen = Rcpp::wrap(mu_SR(a_0, a_1, a_2, a_3, d));
    return rcpp_result_gen;
END_RCPP
}
// get_integration_failures
int get_integration_failures();
RcppExport SEXP _CppTrials_get_integration_failures() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(get_integration_failures());
    return rcpp_result_gen;
END_RCPP
}
// reset_integration_failures
void reset_integration_failures();
RcppExport SEXP _CppTrials_reset_integration_failures() {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    reset_integration_failures();
    return R_NilValue;
END_RCPP
}
// joint_prob
NumericMatrix joint_prob(List t_bound, List r_bound, double mu_T, double mu_R, double sig1, double rho, IntegerVector K);
RcppExport SEXP _CppTrials_joint_prob(SEXP t_boundSEXP, SEXP r_boundSEXP, SEXP mu_TSEXP, SEXP mu_RSEXP, SEXP sig1SEXP, SEXP rhoSEXP, SEXP KSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type t_bound(t_boundSEXP);
    Rcpp::traits::input_parameter< List >::type r_bound(r_boundSEXP);
    Rcpp::traits::input_parameter< double >::type mu_T(mu_TSEXP);
    Rcpp::traits::input_parameter< double >::type mu_R(mu_RSEXP);
    Rcpp::traits::input_parameter< double >::type sig1(sig1SEXP);
    Rcpp::traits::input_parameter< double >::type rho(rhoSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type K(KSEXP);
    rcpp_result_gen = Rcpp::wrap(joint_prob(t_bound, r_bound, mu_T, mu_R, sig1, rho, K));
    return rcpp_result_gen;
END_RCPP
}
// pi_jk_fxn
List pi_jk_fxn(NumericVector e_T, NumericVector e_R, double a_0, double a_1, double a_2, double a_3, double b_0, double b_1, double sig1, double rho, NumericVector std_d, int n_doses, IntegerVector K);
RcppExport SEXP _CppTrials_pi_jk_fxn(SEXP e_TSEXP, SEXP e_RSEXP, SEXP a_0SEXP, SEXP a_1SEXP, SEXP a_2SEXP, SEXP a_3SEXP, SEXP b_0SEXP, SEXP b_1SEXP, SEXP sig1SEXP, SEXP rhoSEXP, SEXP std_dSEXP, SEXP n_dosesSEXP, SEXP KSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type e_T(e_TSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type e_R(e_RSEXP);
    Rcpp::traits::input_parameter< double >::type a_0(a_0SEXP);
    Rcpp::traits::input_parameter< double >::type a_1(a_1SEXP);
    Rcpp::traits::input_parameter< double >::type a_2(a_2SEXP);
    Rcpp::traits::input_parameter< double >::type a_3(a_3SEXP);
    Rcpp::traits::input_parameter< double >::type b_0(b_0SEXP);
    Rcpp::traits::input_parameter< double >::type b_1(b_1SEXP);
    Rcpp::traits::input_parameter< double >::type sig1(sig1SEXP);
    Rcpp::traits::input_parameter< double >::type rho(rhoSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type std_d(std_dSEXP);
    Rcpp::traits::input_parameter< int >::type n_doses(n_dosesSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type K(KSEXP);
    rcpp_result_gen = Rcpp::wrap(pi_jk_fxn(e_T, e_R, a_0, a_1, a_2, a_3, b_0, b_1, sig1, rho, std_d, n_doses, K));
    return rcpp_result_gen;
END_RCPP
}
// Exp_U
NumericVector Exp_U(List pi_jk, NumericMatrix utility_mat, int n_doses);
RcppExport SEXP _CppTrials_Exp_U(SEXP pi_jkSEXP, SEXP utility_matSEXP, SEXP n_dosesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type pi_jk(pi_jkSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type utility_mat(utility_matSEXP);
    Rcpp::traits::input_parameter< int >::type n_doses(n_dosesSEXP);
    rcpp_result_gen = Rcpp::wrap(Exp_U(pi_jk, utility_mat, n_doses));
    return rcpp_result_gen;
END_RCPP
}
// run_sampler
List run_sampler(int N, int burn, int thin_by, NumericVector y_T_vec, NumericVector y_R_vec, NumericVector d, NumericVector doses, int nt, int n_doses, double cur_a_0, double cur_a_1, double cur_a_2, double cur_a_3, double cur_b_0, double cur_b_1, NumericVector cur_lamb_T, NumericVector cur_lamb_R, double cur_rho, NumericVector cur_z, NumericVector mu_T, NumericVector mu_R, NumericVector alpha_bar, NumericVector w, NumericVector beta_bar, NumericVector nu, double eta_T, double eta_R, double a_rho, double b_rho, double sig_2, IntegerVector K, NumericMatrix Ut_mat, NumericVector doses_mg);
RcppExport SEXP _CppTrials_run_sampler(SEXP NSEXP, SEXP burnSEXP, SEXP thin_bySEXP, SEXP y_T_vecSEXP, SEXP y_R_vecSEXP, SEXP dSEXP, SEXP dosesSEXP, SEXP ntSEXP, SEXP n_dosesSEXP, SEXP cur_a_0SEXP, SEXP cur_a_1SEXP, SEXP cur_a_2SEXP, SEXP cur_a_3SEXP, SEXP cur_b_0SEXP, SEXP cur_b_1SEXP, SEXP cur_lamb_TSEXP, SEXP cur_lamb_RSEXP, SEXP cur_rhoSEXP, SEXP cur_zSEXP, SEXP mu_TSEXP, SEXP mu_RSEXP, SEXP alpha_barSEXP, SEXP wSEXP, SEXP beta_barSEXP, SEXP nuSEXP, SEXP eta_TSEXP, SEXP eta_RSEXP, SEXP a_rhoSEXP, SEXP b_rhoSEXP, SEXP sig_2SEXP, SEXP KSEXP, SEXP Ut_matSEXP, SEXP doses_mgSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type N(NSEXP);
    Rcpp::traits::input_parameter< int >::type burn(burnSEXP);
    Rcpp::traits::input_parameter< int >::type thin_by(thin_bySEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y_T_vec(y_T_vecSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y_R_vec(y_R_vecSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type d(dSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type doses(dosesSEXP);
    Rcpp::traits::input_parameter< int >::type nt(ntSEXP);
    Rcpp::traits::input_parameter< int >::type n_doses(n_dosesSEXP);
    Rcpp::traits::input_parameter< double >::type cur_a_0(cur_a_0SEXP);
    Rcpp::traits::input_parameter< double >::type cur_a_1(cur_a_1SEXP);
    Rcpp::traits::input_parameter< double >::type cur_a_2(cur_a_2SEXP);
    Rcpp::traits::input_parameter< double >::type cur_a_3(cur_a_3SEXP);
    Rcpp::traits::input_parameter< double >::type cur_b_0(cur_b_0SEXP);
    Rcpp::traits::input_parameter< double >::type cur_b_1(cur_b_1SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type cur_lamb_T(cur_lamb_TSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type cur_lamb_R(cur_lamb_RSEXP);
    Rcpp::traits::input_parameter< double >::type cur_rho(cur_rhoSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type cur_z(cur_zSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type mu_T(mu_TSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type mu_R(mu_RSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type alpha_bar(alpha_barSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type w(wSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type beta_bar(beta_barSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type nu(nuSEXP);
    Rcpp::traits::input_parameter< double >::type eta_T(eta_TSEXP);
    Rcpp::traits::input_parameter< double >::type eta_R(eta_RSEXP);
    Rcpp::traits::input_parameter< double >::type a_rho(a_rhoSEXP);
    Rcpp::traits::input_parameter< double >::type b_rho(b_rhoSEXP);
    Rcpp::traits::input_parameter< double >::type sig_2(sig_2SEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type K(KSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type Ut_mat(Ut_matSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type doses_mg(doses_mgSEXP);
    rcpp_result_gen = Rcpp::wrap(run_sampler(N, burn, thin_by, y_T_vec, y_R_vec, d, doses, nt, n_doses, cur_a_0, cur_a_1, cur_a_2, cur_a_3, cur_b_0, cur_b_1, cur_lamb_T, cur_lamb_R, cur_rho, cur_z, mu_T, mu_R, alpha_bar, w, beta_bar, nu, eta_T, eta_R, a_rho, b_rho, sig_2, K, Ut_mat, doses_mg));
    return rcpp_result_gen;
END_RCPP
}
// U_low_fxn
double U_low_fxn(NumericVector h_T, NumericVector h_R, double sigma, NumericMatrix Ut_mat, IntegerVector K);
RcppExport SEXP _CppTrials_U_low_fxn(SEXP h_TSEXP, SEXP h_RSEXP, SEXP sigmaSEXP, SEXP Ut_matSEXP, SEXP KSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type h_T(h_TSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type h_R(h_RSEXP);
    Rcpp::traits::input_parameter< double >::type sigma(sigmaSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type Ut_mat(Ut_matSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type K(KSEXP);
    rcpp_result_gen = Rcpp::wrap(U_low_fxn(h_T, h_R, sigma, Ut_mat, K));
    return rcpp_result_gen;
END_RCPP
}
// run_trial_ubr
List run_trial_ubr(int co_sz, int n_doses, NumericVector doses, NumericVector std_d_doses, List pi_jk, int N_max, double cu_star, double U_low, int n_balls, int N, int burn, int thin_by, NumericVector alpha_bar, NumericVector w, NumericVector beta_bar, NumericVector nu, Rcpp::Nullable<double> eta_T, Rcpp::Nullable<double> eta_R, double a_rho, double b_rho, double sig_2, IntegerVector K, NumericMatrix Ut_mat, Rcpp::Nullable<Rcpp::List> init_values);
RcppExport SEXP _CppTrials_run_trial_ubr(SEXP co_szSEXP, SEXP n_dosesSEXP, SEXP dosesSEXP, SEXP std_d_dosesSEXP, SEXP pi_jkSEXP, SEXP N_maxSEXP, SEXP cu_starSEXP, SEXP U_lowSEXP, SEXP n_ballsSEXP, SEXP NSEXP, SEXP burnSEXP, SEXP thin_bySEXP, SEXP alpha_barSEXP, SEXP wSEXP, SEXP beta_barSEXP, SEXP nuSEXP, SEXP eta_TSEXP, SEXP eta_RSEXP, SEXP a_rhoSEXP, SEXP b_rhoSEXP, SEXP sig_2SEXP, SEXP KSEXP, SEXP Ut_matSEXP, SEXP init_valuesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type co_sz(co_szSEXP);
    Rcpp::traits::input_parameter< int >::type n_doses(n_dosesSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type doses(dosesSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type std_d_doses(std_d_dosesSEXP);
    Rcpp::traits::input_parameter< List >::type pi_jk(pi_jkSEXP);
    Rcpp::traits::input_parameter< int >::type N_max(N_maxSEXP);
    Rcpp::traits::input_parameter< double >::type cu_star(cu_starSEXP);
    Rcpp::traits::input_parameter< double >::type U_low(U_lowSEXP);
    Rcpp::traits::input_parameter< int >::type n_balls(n_ballsSEXP);
    Rcpp::traits::input_parameter< int >::type N(NSEXP);
    Rcpp::traits::input_parameter< int >::type burn(burnSEXP);
    Rcpp::traits::input_parameter< int >::type thin_by(thin_bySEXP);
    Rcpp::traits::input_parameter< NumericVector >::type alpha_bar(alpha_barSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type w(wSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type beta_bar(beta_barSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type nu(nuSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<double> >::type eta_T(eta_TSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<double> >::type eta_R(eta_RSEXP);
    Rcpp::traits::input_parameter< double >::type a_rho(a_rhoSEXP);
    Rcpp::traits::input_parameter< double >::type b_rho(b_rhoSEXP);
    Rcpp::traits::input_parameter< double >::type sig_2(sig_2SEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type K(KSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type Ut_mat(Ut_matSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::List> >::type init_values(init_valuesSEXP);
    rcpp_result_gen = Rcpp::wrap(run_trial_ubr(co_sz, n_doses, doses, std_d_doses, pi_jk, N_max, cu_star, U_low, n_balls, N, burn, thin_by, alpha_bar, w, beta_bar, nu, eta_T, eta_R, a_rho, b_rho, sig_2, K, Ut_mat, init_values));
    return rcpp_result_gen;
END_RCPP
}
// run_trial_mpbr
List run_trial_mpbr(int co_sz, int n_doses, NumericVector doses, NumericVector std_d_doses, List pi_jk, int N_max, int n_balls, double cu_star_T, double cu_star_R, int h_T, int h_R, double upper_xi_T, double lower_xi_R, int N, int burn, int thin_by, NumericVector alpha_bar, NumericVector w, NumericVector beta_bar, NumericVector nu, Rcpp::Nullable<double> eta_T, Rcpp::Nullable<double> eta_R, double a_rho, double b_rho, double sig_2, IntegerVector K, NumericMatrix Ut_mat, Rcpp::Nullable<Rcpp::List> init_values);
RcppExport SEXP _CppTrials_run_trial_mpbr(SEXP co_szSEXP, SEXP n_dosesSEXP, SEXP dosesSEXP, SEXP std_d_dosesSEXP, SEXP pi_jkSEXP, SEXP N_maxSEXP, SEXP n_ballsSEXP, SEXP cu_star_TSEXP, SEXP cu_star_RSEXP, SEXP h_TSEXP, SEXP h_RSEXP, SEXP upper_xi_TSEXP, SEXP lower_xi_RSEXP, SEXP NSEXP, SEXP burnSEXP, SEXP thin_bySEXP, SEXP alpha_barSEXP, SEXP wSEXP, SEXP beta_barSEXP, SEXP nuSEXP, SEXP eta_TSEXP, SEXP eta_RSEXP, SEXP a_rhoSEXP, SEXP b_rhoSEXP, SEXP sig_2SEXP, SEXP KSEXP, SEXP Ut_matSEXP, SEXP init_valuesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type co_sz(co_szSEXP);
    Rcpp::traits::input_parameter< int >::type n_doses(n_dosesSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type doses(dosesSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type std_d_doses(std_d_dosesSEXP);
    Rcpp::traits::input_parameter< List >::type pi_jk(pi_jkSEXP);
    Rcpp::traits::input_parameter< int >::type N_max(N_maxSEXP);
    Rcpp::traits::input_parameter< int >::type n_balls(n_ballsSEXP);
    Rcpp::traits::input_parameter< double >::type cu_star_T(cu_star_TSEXP);
    Rcpp::traits::input_parameter< double >::type cu_star_R(cu_star_RSEXP);
    Rcpp::traits::input_parameter< int >::type h_T(h_TSEXP);
    Rcpp::traits::input_parameter< int >::type h_R(h_RSEXP);
    Rcpp::traits::input_parameter< double >::type upper_xi_T(upper_xi_TSEXP);
    Rcpp::traits::input_parameter< double >::type lower_xi_R(lower_xi_RSEXP);
    Rcpp::traits::input_parameter< int >::type N(NSEXP);
    Rcpp::traits::input_parameter< int >::type burn(burnSEXP);
    Rcpp::traits::input_parameter< int >::type thin_by(thin_bySEXP);
    Rcpp::traits::input_parameter< NumericVector >::type alpha_bar(alpha_barSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type w(wSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type beta_bar(beta_barSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type nu(nuSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<double> >::type eta_T(eta_TSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<double> >::type eta_R(eta_RSEXP);
    Rcpp::traits::input_parameter< double >::type a_rho(a_rhoSEXP);
    Rcpp::traits::input_parameter< double >::type b_rho(b_rhoSEXP);
    Rcpp::traits::input_parameter< double >::type sig_2(sig_2SEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type K(KSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type Ut_mat(Ut_matSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::List> >::type init_values(init_valuesSEXP);
    rcpp_result_gen = Rcpp::wrap(run_trial_mpbr(co_sz, n_doses, doses, std_d_doses, pi_jk, N_max, n_balls, cu_star_T, cu_star_R, h_T, h_R, upper_xi_T, lower_xi_R, N, burn, thin_by, alpha_bar, w, beta_bar, nu, eta_T, eta_R, a_rho, b_rho, sig_2, K, Ut_mat, init_values));
    return rcpp_result_gen;
END_RCPP
}
// run_trial_veto_ubr
List run_trial_veto_ubr(int co_sz, int n_doses, NumericVector doses, NumericVector std_d_doses, List pi_jk, int N_max, int n_balls, double cu_star_T, double cu_star, int h_T, double upper_xi_T, double U_low, int veto_point, int N, int burn, int thin_by, NumericVector alpha_bar, NumericVector w, NumericVector beta_bar, NumericVector nu, Rcpp::Nullable<double> eta_T, Rcpp::Nullable<double> eta_R, double a_rho, double b_rho, double sig_2, IntegerVector K, NumericMatrix Ut_mat, Rcpp::Nullable<Rcpp::List> init_values);
RcppExport SEXP _CppTrials_run_trial_veto_ubr(SEXP co_szSEXP, SEXP n_dosesSEXP, SEXP dosesSEXP, SEXP std_d_dosesSEXP, SEXP pi_jkSEXP, SEXP N_maxSEXP, SEXP n_ballsSEXP, SEXP cu_star_TSEXP, SEXP cu_starSEXP, SEXP h_TSEXP, SEXP upper_xi_TSEXP, SEXP U_lowSEXP, SEXP veto_pointSEXP, SEXP NSEXP, SEXP burnSEXP, SEXP thin_bySEXP, SEXP alpha_barSEXP, SEXP wSEXP, SEXP beta_barSEXP, SEXP nuSEXP, SEXP eta_TSEXP, SEXP eta_RSEXP, SEXP a_rhoSEXP, SEXP b_rhoSEXP, SEXP sig_2SEXP, SEXP KSEXP, SEXP Ut_matSEXP, SEXP init_valuesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type co_sz(co_szSEXP);
    Rcpp::traits::input_parameter< int >::type n_doses(n_dosesSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type doses(dosesSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type std_d_doses(std_d_dosesSEXP);
    Rcpp::traits::input_parameter< List >::type pi_jk(pi_jkSEXP);
    Rcpp::traits::input_parameter< int >::type N_max(N_maxSEXP);
    Rcpp::traits::input_parameter< int >::type n_balls(n_ballsSEXP);
    Rcpp::traits::input_parameter< double >::type cu_star_T(cu_star_TSEXP);
    Rcpp::traits::input_parameter< double >::type cu_star(cu_starSEXP);
    Rcpp::traits::input_parameter< int >::type h_T(h_TSEXP);
    Rcpp::traits::input_parameter< double >::type upper_xi_T(upper_xi_TSEXP);
    Rcpp::traits::input_parameter< double >::type U_low(U_lowSEXP);
    Rcpp::traits::input_parameter< int >::type veto_point(veto_pointSEXP);
    Rcpp::traits::input_parameter< int >::type N(NSEXP);
    Rcpp::traits::input_parameter< int >::type burn(burnSEXP);
    Rcpp::traits::input_parameter< int >::type thin_by(thin_bySEXP);
    Rcpp::traits::input_parameter< NumericVector >::type alpha_bar(alpha_barSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type w(wSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type beta_bar(beta_barSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type nu(nuSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<double> >::type eta_T(eta_TSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<double> >::type eta_R(eta_RSEXP);
    Rcpp::traits::input_parameter< double >::type a_rho(a_rhoSEXP);
    Rcpp::traits::input_parameter< double >::type b_rho(b_rhoSEXP);
    Rcpp::traits::input_parameter< double >::type sig_2(sig_2SEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type K(KSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type Ut_mat(Ut_matSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::List> >::type init_values(init_valuesSEXP);
    rcpp_result_gen = Rcpp::wrap(run_trial_veto_ubr(co_sz, n_doses, doses, std_d_doses, pi_jk, N_max, n_balls, cu_star_T, cu_star, h_T, upper_xi_T, U_low, veto_point, N, burn, thin_by, alpha_bar, w, beta_bar, nu, eta_T, eta_R, a_rho, b_rho, sig_2, K, Ut_mat, init_values));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_CppTrials_mu_SR", (DL_FUNC) &_CppTrials_mu_SR, 5},
    {"_CppTrials_get_integration_failures", (DL_FUNC) &_CppTrials_get_integration_failures, 0},
    {"_CppTrials_reset_integration_failures", (DL_FUNC) &_CppTrials_reset_integration_failures, 0},
    {"_CppTrials_joint_prob", (DL_FUNC) &_CppTrials_joint_prob, 7},
    {"_CppTrials_pi_jk_fxn", (DL_FUNC) &_CppTrials_pi_jk_fxn, 13},
    {"_CppTrials_Exp_U", (DL_FUNC) &_CppTrials_Exp_U, 3},
    {"_CppTrials_run_sampler", (DL_FUNC) &_CppTrials_run_sampler, 33},
    {"_CppTrials_U_low_fxn", (DL_FUNC) &_CppTrials_U_low_fxn, 5},
    {"_CppTrials_run_trial_ubr", (DL_FUNC) &_CppTrials_run_trial_ubr, 24},
    {"_CppTrials_run_trial_mpbr", (DL_FUNC) &_CppTrials_run_trial_mpbr, 28},
    {"_CppTrials_run_trial_veto_ubr", (DL_FUNC) &_CppTrials_run_trial_veto_ubr, 28},
    {NULL, NULL, 0}
};

RcppExport void R_init_CppTrials(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
