# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

mu_SR <- function(a_0, a_1, a_2, a_3, d) {
    .Call('_CppTrials_mu_SR', PACKAGE = 'CppTrials', a_0, a_1, a_2, a_3, d)
}

get_integration_failures <- function() {
    .Call('_CppTrials_get_integration_failures', PACKAGE = 'CppTrials')
}

reset_integration_failures <- function() {
    invisible(.Call('_CppTrials_reset_integration_failures', PACKAGE = 'CppTrials'))
}

joint_prob <- function(t_bound, r_bound, mu_T, mu_R, sig1, rho, K) {
    .Call('_CppTrials_joint_prob', PACKAGE = 'CppTrials', t_bound, r_bound, mu_T, mu_R, sig1, rho, K)
}

pi_jk_fxn <- function(e_T, e_R, a_0, a_1, a_2, a_3, b_0, b_1, sig1, rho, std_d, n_doses, K) {
    .Call('_CppTrials_pi_jk_fxn', PACKAGE = 'CppTrials', e_T, e_R, a_0, a_1, a_2, a_3, b_0, b_1, sig1, rho, std_d, n_doses, K)
}

Exp_U <- function(pi_jk, utility_mat, n_doses) {
    .Call('_CppTrials_Exp_U', PACKAGE = 'CppTrials', pi_jk, utility_mat, n_doses)
}

run_sampler <- function(N, burn, thin_by, y_T_vec, y_R_vec, d, doses, nt, n_doses, cur_a_0, cur_a_1, cur_a_2, cur_a_3, cur_b_0, cur_b_1, cur_lamb_T, cur_lamb_R, cur_rho, cur_z, mu_T, mu_R, alpha_bar, w, beta_bar, nu, eta_T, eta_R, a_rho, b_rho, sig_2, K, Ut_mat, doses_mg) {
    .Call('_CppTrials_run_sampler', PACKAGE = 'CppTrials', N, burn, thin_by, y_T_vec, y_R_vec, d, doses, nt, n_doses, cur_a_0, cur_a_1, cur_a_2, cur_a_3, cur_b_0, cur_b_1, cur_lamb_T, cur_lamb_R, cur_rho, cur_z, mu_T, mu_R, alpha_bar, w, beta_bar, nu, eta_T, eta_R, a_rho, b_rho, sig_2, K, Ut_mat, doses_mg)
}

U_low_fxn <- function(h_T, h_R, sigma, Ut_mat, K) {
    .Call('_CppTrials_U_low_fxn', PACKAGE = 'CppTrials', h_T, h_R, sigma, Ut_mat, K)
}

run_trial_ubr <- function(co_sz, n_doses, doses, std_d_doses, pi_jk, N_max, cu_star, U_low, n_balls, N, burn, thin_by, alpha_bar, w, beta_bar, nu, eta_T, eta_R, a_rho, b_rho, sig_2, K, Ut_mat, init_values = NULL) {
    .Call('_CppTrials_run_trial_ubr', PACKAGE = 'CppTrials', co_sz, n_doses, doses, std_d_doses, pi_jk, N_max, cu_star, U_low, n_balls, N, burn, thin_by, alpha_bar, w, beta_bar, nu, eta_T, eta_R, a_rho, b_rho, sig_2, K, Ut_mat, init_values)
}

run_trial_mpbr <- function(co_sz, n_doses, doses, std_d_doses, pi_jk, N_max, n_balls, cu_star_T, cu_star_R, h_T, h_R, upper_xi_T, lower_xi_R, N, burn, thin_by, alpha_bar, w, beta_bar, nu, eta_T, eta_R, a_rho, b_rho, sig_2, K, Ut_mat, init_values = NULL) {
    .Call('_CppTrials_run_trial_mpbr', PACKAGE = 'CppTrials', co_sz, n_doses, doses, std_d_doses, pi_jk, N_max, n_balls, cu_star_T, cu_star_R, h_T, h_R, upper_xi_T, lower_xi_R, N, burn, thin_by, alpha_bar, w, beta_bar, nu, eta_T, eta_R, a_rho, b_rho, sig_2, K, Ut_mat, init_values)
}

run_trial_veto_ubr <- function(co_sz, n_doses, doses, std_d_doses, pi_jk, N_max, n_balls, cu_star_T, cu_star, h_T, upper_xi_T, U_low, veto_point, N, burn, thin_by, alpha_bar, w, beta_bar, nu, eta_T, eta_R, a_rho, b_rho, sig_2, K, Ut_mat, init_values = NULL) {
    .Call('_CppTrials_run_trial_veto_ubr', PACKAGE = 'CppTrials', co_sz, n_doses, doses, std_d_doses, pi_jk, N_max, n_balls, cu_star_T, cu_star, h_T, upper_xi_T, U_low, veto_point, N, burn, thin_by, alpha_bar, w, beta_bar, nu, eta_T, eta_R, a_rho, b_rho, sig_2, K, Ut_mat, init_values)
}

